### ISSUE TITLE
robopods 1.25.0 not working with Firebase 9.4.0

### ISSUE THREAD

**Issue by DavidPDev** [dkimitsa/robovm-robopods#18]
I created a related issue on the main robovm project, but now I realize that this might be a better place:
https://github.com/MobiVM/robovm/issues/687

Well, doing many other tests I used the recommended 1.25.0 robopods version, with robovm 2.3.18 and libgdx 1.11.0.
Dowloaded the firebase.zip 9.4.0 files.
When launching i get this errors (hundreds of warnings and final fatal error)

```
> Task :ios:launchIPhoneSimulator
RoboVM has detected that you are running on a slow HDD. Please consider mounting a RAM disk.
To create a 2GB RAM disk, run this in your terminal:
SIZE=2048 ; diskutil erasevolume HFS+ 'RoboVM RAM Disk' `hdiutil attach -nomount ram://$((SIZE * 2048))`
See http://docs.robovm.com/ for more info
ld: warning: object file (/Users/david/.robovm/cache/ios/x86_64-simulator/release/Users/david/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-freetype-platform/1.11.0/c4c8c613b95b067af4f0928669077e7ad2585206/gdx-freetype-platform-1.11.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs/gdx-freetype.xcframework/ios-arm64_x86_64-simulator/libgdx-freetype.a(com_badlogic_gdx_graphics_g2d_freetype_FreeType.o)) was built for newer iOS Simulator version (9.0) than being linked (8.0)
ld: warning: object file (/Users/david/.robovm/cache/ios/x86_64-simulator/release/Users/david/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.11.0/a55afe221d06ea79c011fa235971eae22aa9419d/gdx-platform-1.11.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs/ObjectAL.xcframework/ios-arm64_x86_64-simulator/libObjectAL.a(OALAction.o)) was built for newer iOS Simulator version (9.0) than being linked (8.0)
```

**Comment by dkimitsa** [comment]
hi, 
can't see any error message in your report above. 
regarding https://github.com/MobiVM/robovm/issues/687 here are few moments:
* there is alt-pods 1.26.0 with support of FB 10 deployed
* you warnings are related to missing `<swiftSupport/>` entry in `robovm.xml`
* linker complaints that you target ios8 while dependencies you are using compiled for ios9/10 min 

source code for 1.26.0 https://github.com/dkimitsa/robovm-robopods/tree/dev/v1.26.0
test snippets: https://github.com/dkimitsa/alt-pods-tests

**Comment by DavidPDev** [comment]
Thank you for your quick reply @dkimitsa !
The problem is that the firebase.zip 10.0.0 has changed some file names, so now there is some kind of mess in the dependencies

For example:
https://github.com/dkimitsa/robovm-robopods/tree/dev/v1.26.0/firebase/ios-core

![image](https://user-images.githubusercontent.com/25801199/198022897-ba76af27-dc4b-45af-bf64-42438859cc0a.png)

The PromisesObjC is missing in the firebase.zip bundle, now it is named as FBLPromises

**Comment by dkimitsa** [comment]
@DavidPDev thx for pointing -- readme is not updated. but bindings were fixed. have tested today.
also you can check alt-pod-tests from link above

**Comment by DavidPDev** [comment]
Ok, Thank you! I'll test it again!

**Comment by dkimitsa** [comment]
have updated readme files, please let me know if there is any misstake around.
thx

**Comment by DavidPDev** [comment]
Thank you @dkimitsa!
Well, now seems to work, I have to do some more tests and create the IPA file to complete all the cycle.
I am having many warnings but don't affect.
Also I was missing the ``` <swiftSupport/> ``` key

Just a question, is there any way to debug in the simulator? when I add a breakpoint in IDEA it doesn't stop.
Thank you again for your great work.

**Comment by dkimitsa** [comment]
thanks for update, regarding debugger/warnings feel free writing to [gitter channel](https://github.com/MobiVM/robovm)
meanwhile closing this as resolved. 
thx

**Comment by DavidPDev** [comment]
Trying to create the IPA file I get this error:

```
[ERROR] 20:04:53.850 ld: framework not found FirebaseCoreDiagnostics
[ERROR] 20:04:53.851 clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't create IPA
org.apache.commons.exec.ExecuteException: Command '[/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++, ...@loader_path/Frameworks]' failed  (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.robovm.compiler.util.Executor.exec(Executor.java:344)
	at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:404)
	at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:271)
	at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:333)
	at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:264)
	at org.robovm.compiler.Linker.link(Linker.java:449)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:518)
	at org.robovm.compiler.AppCompiler.build(AppCompiler.java:955)
	at org.robovm.idea.compilation.RoboVmCompileTask$1.doCompile(RoboVmCompileTask.java:107)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:69)

```

I added the FirebaseCoreDiagnostics library and then the error of missing PromisesObjC rises again.

**Comment by dkimitsa** [comment]
@DavidPDev 
FirebaseCoreDiagnostics is not part of Firebase10 or 1.26.0 bindings. Check if you have referenced it in robovm.xml and version of alt-pods you are using

**Comment by DavidPDev** [comment]
Thank you again!
I finally managed to build the .IPA file using the task::mobivm::createIPA.
But, from the main menu RoboVM/Create IPA doesn't work. So, maybe the menu options (RoboVM) are deprecated?

**Comment by dkimitsa** [comment]
how exactly `RoboVM/Create` doesn't work ? its better to discuss things in [gitter](https://github.com/MobiVM/robovm)
