### ISSUE TITLE
Unable to compile FirebaseStorage

### ISSUE THREAD

**Issue by Tonielro** [dkimitsa/robovm-robopods#19]
Each time I try to deploy my app to my device it fails. The issue started when  I added Firebase Storage framework to my app.

The key error is "[ERROR] 19:20:47.969 ld: symbol(s) not found for architecture arm64"

I have added all the needed Firebase frameworks that are required by Firebase Storage.

The error log is too long. Below is the brief error log

[ERROR] 19:49:38.027 Undefined symbols for architecture arm64:
[ERROR] 19:49:38.027   "_$s15_ObjectiveCTypes01_A11CBridgeablePTl", referenced from:
[ERROR] 19:49:38.041       l_got.$s15_ObjectiveCTypes01_A11CBridgeablePTl in FirebaseStorage(AsyncAwait.o)
[ERROR] 19:49:38.298   "_$s7ElementSTTl", referenced from:
[ERROR] 19:49:38.320       l_got.$s7ElementSTTl in FirebaseCoreInternal(RingBuffer.o)
[ERROR] 19:49:38.561   "_$s8AllCasess12CaseIterablePTl", referenced from:
[ERROR] 19:49:38.578       l_got.$s8AllCasess12CaseIterablePTl in FirebaseCoreInternal(Heartbeat.o)
[ERROR] 19:49:38.863   "_$s8Dispatch0A13WorkItemFlagsVMa", referenced from:
[ERROR] 19:49:38.884       _$s15FirebaseStorage0B15TokenAuthorizerC16authorizeRequest_17completionHandlerySo19NSMutableURLRequestCSg_ys5Error_pSgctF in FirebaseStorage(StorageTokenAuthorizer.o)
[ERROR] 19:49:38.884       _$s8Dispatch0A13WorkItemFlagsVACs10SetAlgebraAAWl in FirebaseStorage(StorageTokenAuthorizer.o)
[ERROR] 19:49:38.884       _$sSay8Dispatch0A13WorkItemFlagsVGSayxGSTsWl in FirebaseStorage(StorageTokenAuthorizer.o)
[ERROR] 19:49:38.884       _$sSay8Dispatch0A13WorkItemFlagsVGMa in FirebaseStorage(StorageTokenAuthorizer.o)
[ERROR] 19:49:38.884       _$s15FirebaseStorage0B18UpdateMetadataTaskC7enqueueyyF in FirebaseStorage(StorageUpdateMetadataTask.o)
[ERROR] 19:49:38.884       _$s15FirebaseStorage0B10DeleteTaskC7enqueueyyF in FirebaseStorage(StorageDeleteTask.o)
[ERROR] 19:49:38.884       _$s15FirebaseStorage0B14ObservableTaskC4fire8handlers8snapshotySDySSyAA0bD8SnapshotCcG_AHtF in FirebaseStorage(StorageObservableTask.o)
[ERROR] 19:49:38.884       ...
[ERROR] 19:49:39.146   "_$s8Dispatch0A13WorkItemFlagsVMn", referenced from:
[ERROR] 19:49:39.163       _symbolic Say_____G 8Dispatch0A13WorkItemFlagsV in FirebaseStorage(StorageTokenAuthorizer.o)
[ERROR] 19:49:39.163       _symbolic Say_____G 8Dispatch0A13WorkItemFlagsV in FirebaseStorage(StorageUpdateMetadataTask.o)
[ERROR] 19:49:39.163       _symbolic Say_____G 8Dispatch0A13WorkItemFlagsV in FirebaseStorage(StorageDeleteTask.o)
[ERROR] 19:49:39.163       _symbolic Say_____G 8Dispatch0A13WorkItemFlagsV in FirebaseStorage(StorageObservableTask.o)
[ERROR] 19:49:39.163       _symbolic Say_____G 8Dispatch0A13WorkItemFlagsV in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:39.163       _symbolic Say_____G 8Dispatch0A13WorkItemFlagsV in FirebaseStorage(StorageGetMetadataTask.o)
[ERROR] 19:49:39.163       _symbolic Say_____G 8Dispatch0A13WorkItemFlagsV in FirebaseStorage(StorageReference.o)
[ERROR] 19:49:39.163       ...
[ERROR] 19:49:39.399   "_$s8Dispatch0A13WorkItemFlagsVs10SetAlgebraAAMc", referenced from:
[ERROR] 19:49:39.416       _$s15FirebaseStorage0B15TokenAuthorizerC16authorizeRequest_17completionHandlerySo19NSMutableURLRequestCSg_ys5Error_pSgctF in FirebaseStorage(StorageTokenAuthorizer.o)
[ERROR] 19:49:39.416       _$s8Dispatch0A13WorkItemFlagsVACs10SetAlgebraAAWl in FirebaseStorage(StorageTokenAuthorizer.o)
[ERROR] 19:49:39.416       _$s15FirebaseStorage0B18UpdateMetadataTaskC7enqueueyyF in FirebaseStorage(StorageUpdateMetadataTask.o)
[ERROR] 19:49:39.416       _$s15FirebaseStorage0B10DeleteTaskC7enqueueyyF in FirebaseStorage(StorageDeleteTask.o)
[ERROR] 19:49:39.416       _$s15FirebaseStorage0B12DownloadTaskC5pauseyyF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:39.416       _$s15FirebaseStorage0B12DownloadTaskC6resumeyyF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:39.416       _$s15FirebaseStorage0B12DownloadTaskC21enqueueImplementation10resumeWithy10Foundation4DataVSg_tF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:39.416       ...
[ERROR] 19:49:39.640   "_$s8Dispatch0A3QoSV0B6SClassO10backgroundyA2EmFWC", referenced from:
[ERROR] 19:49:39.656       _$s15FirebaseStorage0B18UpdateMetadataTaskC7enqueueyyF in FirebaseStorage(StorageUpdateMetadataTask.o)
[ERROR] 19:49:39.656       _$s15FirebaseStorage0B10DeleteTaskC7enqueueyyF in FirebaseStorage(StorageDeleteTask.o)
[ERROR] 19:49:39.656       _$s15FirebaseStorage0B12DownloadTaskC5pauseyyF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:39.656       _$s15FirebaseStorage0B12DownloadTaskC6resumeyyF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:39.656       _$s15FirebaseStorage0B12DownloadTaskC21enqueueImplementation10resumeWithy10Foundation4DataVSg_tF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:39.656       _$s15FirebaseStorage0B12DownloadTaskC6cancel9withErrorySo7NSErrorC_tF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:39.656       _$s15FirebaseStorage0B15GetMetadataTaskC7enqueueyyF in FirebaseStorage(StorageGetMetadataTask.o)
[ERROR] 19:49:39.656       ...
[ERROR] 19:49:39.882   "_$s8Dispatch0A3QoSV0B6SClassOMa", referenced from:
[ERROR] 19:49:39.899       _$s15FirebaseStorage0B18UpdateMetadataTaskC7enqueueyyF in FirebaseStorage(StorageUpdateMetadataTask.o)
[ERROR] 19:49:39.899       _$s15FirebaseStorage0B10DeleteTaskC7enqueueyyF in FirebaseStorage(StorageDeleteTask.o)
[ERROR] 19:49:39.899       _$s15FirebaseStorage0B12DownloadTaskC5pauseyyF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:39.899       _$s15FirebaseStorage0B12DownloadTaskC6resumeyyF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:39.899       _$s15FirebaseStorage0B12DownloadTaskC21enqueueImplementation10resumeWithy10Foundation4DataVSg_tF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:39.899       _$s15FirebaseStorage0B12DownloadTaskC6cancel9withErrorySo7NSErrorC_tF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:39.899       _$s15FirebaseStorage0B15GetMetadataTaskC7enqueueyyF in FirebaseStorage(StorageGetMetadataTask.o)
[ERROR] 19:49:39.899       ...
[ERROR] 19:49:40.160   "_$s8Dispatch0A3QoSV11unspecifiedACvgZ", referenced from:
[ERROR] 19:49:40.177       _$s15FirebaseStorage0B15TokenAuthorizerC16authorizeRequest_17completionHandlerySo19NSMutableURLRequestCSg_ys5Error_pSgctF in FirebaseStorage(StorageTokenAuthorizer.o)
[ERROR] 19:49:40.177       _$s15FirebaseStorage0B15TokenAuthorizerC11googleAppID14fetcherService12authProvider8appCheckACSS_So017GTMSessionFetcherI0CSo14FIRAuthInterop_pSgSo06FIRAppmQ0_pSgtcfcTf4ggggn_n in FirebaseStorage(StorageTokenAuthorizer.o)
[ERROR] 19:49:40.177       _$s15FirebaseStorage0B18UpdateMetadataTaskC7enqueueyyF in FirebaseStorage(StorageUpdateMetadataTask.o)
[ERROR] 19:49:40.177       _$s15FirebaseStorage0B10DeleteTaskC7enqueueyyF in FirebaseStorage(StorageDeleteTask.o)
[ERROR] 19:49:40.177       _$s15FirebaseStorage0B14ObservableTaskC4fire8handlers8snapshotySDySSyAA0bD8SnapshotCcG_AHtF in FirebaseStorage(StorageObservableTask.o)
[ERROR] 19:49:40.177       _$s15FirebaseStorage0B12DownloadTaskC5pauseyyF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:40.177       _$s15FirebaseStorage0B12DownloadTaskC6resumeyyF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:40.177       ...
[ERROR] 19:49:40.405   "_$s8Dispatch0A3QoSVMa", referenced from:
[ERROR] 19:49:40.423       _$s15FirebaseStorage0B15TokenAuthorizerC16authorizeRequest_17completionHandlerySo19NSMutableURLRequestCSg_ys5Error_pSgctF in FirebaseStorage(StorageTokenAuthorizer.o)
[ERROR] 19:49:40.423       _$s15FirebaseStorage0B15TokenAuthorizerC11googleAppID14fetcherService12authProvider8appCheckACSS_So017GTMSessionFetcherI0CSo14FIRAuthInterop_pSgSo06FIRAppmQ0_pSgtcfcTf4ggggn_n in FirebaseStorage(StorageTokenAuthorizer.o)
[ERROR] 19:49:40.423       _$s15FirebaseStorage0B18UpdateMetadataTaskC7enqueueyyF in FirebaseStorage(StorageUpdateMetadataTask.o)
[ERROR] 19:49:40.423       _$s15FirebaseStorage0B10DeleteTaskC7enqueueyyF in FirebaseStorage(StorageDeleteTask.o)
[ERROR] 19:49:40.423       _$s15FirebaseStorage0B14ObservableTaskC4fire8handlers8snapshotySDySSyAA0bD8SnapshotCcG_AHtF in FirebaseStorage(StorageObservableTask.o)
[ERROR] 19:49:40.423       _$s15FirebaseStorage0B12DownloadTaskC5pauseyyF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:40.423       _$s15FirebaseStorage0B12DownloadTaskC6resumeyyF in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:40.423       ...
[ERROR] 19:49:40.659   "_$s8IteratorSTTl", referenced from:
[ERROR] 19:49:40.677       l_got.$s8IteratorSTTl in FirebaseCoreInternal(RingBuffer.o)
[ERROR] 19:49:40.908   "_$s8RawValueSYTl", referenced from:
[ERROR] 19:49:40.928       l_got.$s8RawValueSYTl in FirebaseStorage(AsyncAwait.o)
[ERROR] 19:49:40.928       l_got.$s8RawValueSYTl in FirebaseStorage(StorageConstants.o)
[ERROR] 19:49:40.928       l_got.$s8RawValueSYTl in FirebaseStorage(StorageError.o)
[ERROR] 19:49:40.928       l_got.$s8RawValueSYTl in FirebaseCoreInternal(Heartbeat.o)
[ERROR] 19:49:40.928       l_got.$s8RawValueSYTl in FirebaseCoreInternal(HeartbeatsPayload.o)
[ERROR] 19:49:41.173   "_$sBOWV", referenced from:
[ERROR] 19:49:41.190       _$s15FirebaseStorage0B15TokenAuthorizerCMf in FirebaseStorage(StorageTokenAuthorizer.o)
[ERROR] 19:49:41.190       _$s15FirebaseStorage0B18UpdateMetadataTaskCMr in FirebaseStorage(StorageUpdateMetadataTask.o)
[ERROR] 19:49:41.190       _$s15FirebaseStorage0B18UpdateMetadataTaskCMf in FirebaseStorage(StorageUpdateMetadataTask.o)
[ERROR] 19:49:41.190       _$s15FirebaseStorage0B10DeleteTaskCMf in FirebaseStorage(StorageDeleteTask.o)
[ERROR] 19:49:41.190       _$s15FirebaseStorage0B14ObservableTaskCMf in FirebaseStorage(StorageObservableTask.o)
[ERROR] 19:49:41.190       _$s15FirebaseStorage0B12DownloadTaskCMf in FirebaseStorage(StorageDownloadTask.o)
[ERROR] 19:49:41.190       _$s15FirebaseStorage0B15GetMetadataTaskCMf in FirebaseStorage(StorageGetMetadataTask.o)
[ERROR] 19:49:41.190       ...
[ERROR] 19:49:41.430   "_$sBbWV", referenced from:
[ERROR] 19:49:41.447       _$s15FirebaseStorage0B14ObservableTaskCMr in FirebaseStorage(StorageObservableTask.o)
[ERROR] 19:49:41.447       _$s15FirebaseStorage0B8MetadataCMr in FirebaseStorage(StorageMetadata.o)
[ERROR] 19:49:41.447       _$s20FirebaseCoreInternal9HeartbeatVMr in FirebaseCoreInternal(Heartbeat.o)
[ERROR] 19:49:41.687   "_$sBi32_WV", referenced from:
[ERROR] 19:49:41.704       _$sSo16os_unfair_lock_sVMf in FirebaseStorage(AsyncAwait.o)
[ERROR] 19:49:41.940   "_$sBi64_WV", referenced from:
[ERROR] 19:49:41.960       _$s15FirebaseStorage0B8MetadataCMr in FirebaseStorage(StorageMetadata.o)
[ERROR] 19:49:41.960       _$s15FirebaseStorage0B10TaskStatusOMf in FirebaseStorage(StorageConstants.o)
[ERROR] 19:49:41.960       _$s15FirebaseStorage0B9ErrorCodeOMf in FirebaseStorage(StorageError.o)
[ERROR] 19:49:41.960       _$s20FirebaseCoreInternal9HeartbeatVMr in FirebaseCoreInternal(Heartbeat.o)
[ERROR] 19:49:42.196   "_$sBoWV", referenced from:
[ERROR] 19:49:42.214       _$s15FirebaseStorage0B4PathCMf in FirebaseStorage(StoragePath.o)
[ERROR] 19:49:42.214       _$s15FirebaseStorage0B5UtilsCMf in FirebaseStorage(StorageUtils.o)
[ERROR] 19:49:42.214       _$s20FirebaseCoreInternal19HeartbeatControllerCMf in FirebaseCoreInternal(HeartbeatController.o)
[ERROR] 19:49:42.214       _$s20FirebaseCoreInternal16HeartbeatStorageCMf in FirebaseCoreInternal(HeartbeatStorage.o)
[ERROR] 19:49:42.214       _$s20FirebaseCoreInternal11FileStorageCMf in FirebaseCoreInternal(Storage.o)
[ERROR] 19:49:42.214       _$s20FirebaseCoreInternal19UserDefaultsStorageCMf in FirebaseCoreInternal(Storage.o)
[ERROR] 19:49:42.457   "_$sSD11descriptionSSvg", referenced from:
[ERROR] 19:49:42.474       _$s15FirebaseStorage0B8MetadataC11descriptionSSvg in FirebaseStorage(StorageMetadata.o)
[ERROR] 19:49:42.718   "_$sSDMa", referenced from:
[ERROR] 19:49:42.736       _$sSDyS2SGMaTm in FirebaseStorage(StorageMetadata.o)
[ERROR] 19:49:42.736       _$sSDy20FirebaseCoreInternal10TimePeriodO10Foundation4DateVGMa in FirebaseCoreInternal(HeartbeatsBundle.o)
[ERROR] 19:49:42.977   "_$sSDyxq_GSEsSERzSER_rlMc", referenced from:
[ERROR] 19:49:42.995       _$sSDy20FirebaseCoreInternal10TimePeriodO10Foundation4DateVGSDyxq_GSEsSERzSER_rlWl in FirebaseCoreInternal(HeartbeatsBundle.o)
[ERROR] 19:49:43.234   "_$sSDyxq_GSHsSHR_rlMc", referenced from:
[ERROR] 19:49:43.251       _$sSDyS2SGSDyxq_GSHsSHR_rlWlTm in FirebaseStorage(StorageMetadata.o)
[ERROR] 19:49:43.491   "_$sSDyxq_GSesSeRzSeR_rlMc", referenced from:
[ERROR] 19:49:43.508       _$sSDy20FirebaseCoreInternal10TimePeriodO10Foundation4DateVGSDyxq_GSesSeRzSeR_rlWl in FirebaseCoreInternal(HeartbeatsBundle.o)
[ERROR] 19:49:43.747   "_$sSE6encode2toys7Encoder_p_tKFTq", referenced from:
[ERROR] 19:49:43.763       l_got.$sSE6encode2toys7Encoder_p_tKFTq in FirebaseCoreInternal(Heartbeat.o)
[ERROR] 19:49:43.763       l_got.$sSE6encode2toys7Encoder_p_tKFTq in FirebaseCoreInternal(HeartbeatsBundle.o)
[ERROR] 19:49:43.763       l_got.$sSE6encode2toys7Encoder_p_tKFTq in FirebaseCoreInternal(HeartbeatsPayload.o)
[ERROR] 19:49:43.763       l_got.$sSE6encode2toys7Encoder_p_tKFTq in FirebaseCoreInternal(RingBuffer.o)
[ERROR] 19:49:43.998   "_$sSEMp", referenced from:
[ERROR] 19:49:44.016       l_got.$sSEMp in FirebaseCoreInternal(Heartbeat.o)
[ERROR] 19:49:44.016       l_got.$sSEMp in FirebaseCoreInternal(HeartbeatsBundle.o)
[ERROR] 19:49:44.016       l_got.$sSEMp in FirebaseCoreInternal(HeartbeatsPayload.o)
[ERROR] 19:49:44.016       l_got.$sSEMp in FirebaseCoreInternal(RingBuffer.o)
[ERROR] 19:49:44.260   "_$sSH13_rawHashValue4seedS2i_tFTq", referenced from:
[ERROR] 19:49:44.278       l_got.$sSH13_rawHashValue4seedS2i_tFTq in FirebaseStorage(StorageMetadata.o)
[ERROR] 19:49:44.278       l_got.$sSH13_rawHashValue4seedS2i_tFTq in FirebaseStorage(AsyncAwait.o)
[ERROR] 19:49:44.278       l_got.$sSH13_rawHashValue4seedS2i_tFTq in FirebaseStorage(StorageConstants.o)
[ERROR] 19:49:44.278       l_got.$sSH13_rawHashValue4seedS2i_tFTq in FirebaseStorage(StorageError.o)
[ERROR] 19:49:44.278       l_got.$sSH13_rawHashValue4seedS2i_tFTq in FirebaseStorage(StorageTaskState.o)
[ERROR] 19:49:44.279       l_got.$sSH13_rawHashValue4seedS2i_tFTq in FirebaseCoreInternal(Heartbeat.o)
[ERROR] 19:49:44.279       l_got.$sSH13_rawHashValue4seedS2i_tFTq in FirebaseCoreInternal(HeartbeatsBundle.o)
[ERROR] 19:49:44.279       ...
[ERROR] 19:49:44.515   "_$sSH4hash4intoys6HasherVz_tFTq", referenced from:
[ERROR] 19:49:44.533       l_got.$sSH4hash4intoys6HasherVz_tFTq in FirebaseStorage(StorageMetadata.o)
[ERROR] 19:49:44.533       l_got.$sSH4hash4intoys6HasherVz_tFTq in FirebaseStorage(AsyncAwait.o)
[ERROR] 19:49:44.533       l_got.$sSH4hash4intoys6HasherVz_tFTq in FirebaseStorage(StorageConstants.o)
[ERROR] 19:49:44.533       l_got.$sSH4hash4intoys6HasherVz_tFTq in FirebaseStorage(StorageError.o)
[ERROR] 19:49:44.533       l_got.$sSH4hash4intoys6HasherVz_tFTq in FirebaseStorage(StorageTaskState.o)
[ERROR] 19:49:44.533       l_got.$sSH4hash4intoys6HasherVz_tFTq in FirebaseCoreInternal(Heartbeat.o)
[ERROR] 19:49:44.533       l_got.$sSH4hash4intoys6HasherVz_tFTq in FirebaseCoreInternal(HeartbeatsBundle.o)
[ERROR] 19:49:44.533       ...
[ERROR] 19:49:44.769   "_$sSH9hashValueSivgTq", referenced from:
[ERROR] 19:49:44.784       l_got.$sSH9hashValueSivgTq in FirebaseStorage(StorageMetadata.o)
[ERROR] 19:49:44.784       l_got.$sSH9hashValueSivgTq in FirebaseStorage(AsyncAwait.o)
[ERROR] 19:49:44.784       l_got.$sSH9hashValueSivgTq in FirebaseStorage(StorageConstants.o)
[ERROR] 19:49:44.784       l_got.$sSH9hashValueSivgTq in FirebaseStorage(StorageError.o)
[ERROR] 19:49:44.784       l_got.$sSH9hashValueSivgTq in FirebaseStorage(StorageTaskState.o)
[ERROR] 19:49:44.784       l_got.$sSH9hashValueSivgTq in FirebaseCoreInternal(Heartbeat.o)
[ERROR] 19:49:44.784       l_got.$sSH9hashValueSivgTq in FirebaseCoreInternal(HeartbeatsBundle.o)
[ERROR] 19:49:44.784       ...
[ERROR] 19:49:45.024   "_$sSHMp", referenced from:
[ERROR] 19:49:45.042       l_got.$sSHMp in FirebaseStorage(StorageMetadata.o)
[ERROR] 19:49:45.042       l_got.$sSHMp in FirebaseStorage(AsyncAwait.o)
[ERROR] 19:49:45.042       l_got.$sSHMp in FirebaseStorage(StorageConstants.o)
[ERROR] 19:49:45.042       l_got.$sSHMp in FirebaseStorage(StorageError.o)
[ERROR] 19:49:45.042       l_got.$sSHMp in FirebaseStorage(StorageTaskState.o)
[ERROR] 19:49:45.042       l_got.$sSHMp in FirebaseCoreInternal(Heartbeat.o)
[ERROR] 19:49:45.042       l_got.$sSHMp in FirebaseCoreInternal(HeartbeatsBundle.o)
[ERROR] 19:49:45.042       ...
[ERROR] 19:49:45.284   "_$sSHSQTb", referenced from:
[ERROR] 19:49:45.301       l_got.$sSHSQTb in FirebaseStorage(StorageMetadata.o)
[ERROR] 19:49:45.301       l_got.$sSHSQTb in FirebaseStorage(AsyncAwait.o)
[ERROR] 19:49:45.301       l_got.$sSHSQTb in FirebaseStorage(StorageConstants.o)
[ERROR] 19:49:45.301       l_got.$sSHSQTb in FirebaseStorage(StorageError.o)
[ERROR] 19:49:45.301       l_got.$sSHSQTb in FirebaseStorage(StorageTaskState.o)
[ERROR] 19:49:45.301       l_got.$sSHSQTb in FirebaseCoreInternal(Heartbeat.o)
[ERROR] 19:49:45.301       l_got.$sSHSQTb in FirebaseCoreInternal(HeartbeatsBundle.o)
[ERROR] 19:49:45.301       ...
[ERROR] 19:49:45.544   "_$sSQ2eeoiySbx_xtFZTj", referenced from:
[ERROR] 19:49:45.561       _$sSasSQRzlE2eeoiySbSayxG_ABtFZ20FirebaseCoreInternal17HeartbeatsPayloadV09UserAgentF0V_Tg5Tf4nnd_n in FirebaseCoreInternal(HeartbeatsPayload.o)
[ERROR] 19:49:45.561       _$sSasSQRzlE2eeoiySbSayxG_ABtFZ10Foundation4DateV_Tg5Tf4nnd_n in FirebaseCoreInternal(HeartbeatsPayload.o)
[ERROR] 19:49:45.800   "_$sSQ2eeoiySbx_xtFZTq", referenced from:
[ERROR] 19:49:45.818       l_got.$sSQ2eeoiySbx_xtFZTq in FirebaseStorage(StorageMetadata.o)
[ERROR] 19:49:45.818       l_got.$sSQ2eeoiySbx_xtFZTq in FirebaseStorage(AsyncAwait.o)
[ERROR] 19:49:45.818       l_got.$sSQ2eeoiySbx_xtFZTq in FirebaseStorage(StorageConstants.o)
[ERROR] 19:49:45.818       l_got.$sSQ2eeoiySbx_xtFZTq in FirebaseStorage(StorageError.o)
[ERROR] 19:49:45.818       l_got.$sSQ2eeoiySbx_xtFZTq in FirebaseStorage(StoragePath.o)
[ERROR] 19:49:45.818       l_got.$sSQ2eeoiySbx_xtFZTq in FirebaseStorage(StorageTaskState.o)
[ERROR] 19:49:45.818       l_got.$sSQ2eeoiySbx_xtFZTq in FirebaseCoreInternal(Heartbeat.o)
[ERROR] 19:49:45.818       ...
[ERROR] 19:49:46.054   "_$sSQMp", referenced from:
[ERROR] 19:49:46.071       l_got.$sSQMp in FirebaseStorage(StorageMetadata.o)
[ERROR] 19:49:46.071       l_got.$sSQMp in FirebaseStorage(AsyncAwait.o)
[ERROR] 19:49:46.072       l_got.$sSQMp in FirebaseStorage(StorageConstants.o)
[ERROR] 19:49:46.072       l_got.$sSQMp in FirebaseStorage(StorageError.o)
[ERROR] 19:49:46.072       l_got.$sSQMp in FirebaseStorage(StoragePath.o)
[ERROR] 19:49:46.072       l_got.$sSQMp in FirebaseStorage(StorageTaskState.o)
[ERROR] 19:49:46.072       l_got.$sSQMp in FirebaseCoreInternal(Heartbeat.o)
[ERROR] 19:49:46.072       ...
[ERROR] 19:49:46.311   "_$sSS10describingSSx_tclufC", referenced from:
[ERROR] 19:49:46.328       _$s15FirebaseStorage0B12TaskSnapshotC11descriptionSSvg in FirebaseStorage(StorageTaskSnapshot.o)
[ERROR] 19:49:46.567   "_$sSS14_fromSubstringySSSshFZ", referenced from:
[ERROR] 19:49:46.585       _$s15FirebaseStorage0B10ListResultC4with9referenceACSDySSypG_AA0B9ReferenceCtcfCTf4ggd_n in FirebaseStorage(StorageListResult.o)
[ERROR] 19:49:46.585       _$s15FirebaseStorage0B4PathC4path5GSURIACSS_tKFZTf4nd_n in FirebaseStorage(StoragePath.o)
[ERROR] 19:49:46.819   "_$sSS18_uncheckedFromUTF8ySSSRys5UInt8VGFZ", referenced from:
[ERROR] 19:49:46.837       _$sSS8_copyingySSSsFZ in FirebaseStorage(StorageMetadata.o)
[ERROR] 19:49:46.837       _$sSS8_copyingySSSsFZSSSRys5UInt8VGXEfU0_ in FirebaseStorage(StorageMetadata.o)
[ERROR] 19:49:47.067   "_$sSS4hash4intoys6HasherVz_tF", referenced from:
[ERROR] 19:49:47.085       _$ss22__RawDictionaryStorageC4findys10_HashTableV6BucketV6bucket_Sb5foundtxSHRzlFSS_Tg5 in FirebaseStorage(StorageObservableTask.o)
[ERROR] 19:49:47.085       _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_y15FirebaseStorage0L12TaskSnapshotCcTg5 in FirebaseStorage(StorageObservableTask.o)
[ERROR] 19:49:47.085       _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_15FirebaseStorage0L10TaskStatusOTg5 in FirebaseStorage(StorageObservableTask.o)
[ERROR] 19:49:47.085       _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_SDySSSo24GTMSessionFetcherServiceCGTg5 in FirebaseStorage(StorageObservableTask.o)
[ERROR] 19:49:47.085       _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_So24GTMSessionFetcherServiceCTg5Tm in FirebaseStorage(StorageObservableTask.o)
[ERROR] 19:49:47.085       _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_ypTg5 in FirebaseStorage(StorageObservableTask.o)
[ERROR] 19:49:47.085       _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_SSTg5 in FirebaseStorage(StorageObservableTask.o)
[ERROR] 19:49:47.085       ...
[ERROR] 19:49:47.329   "_$sSS5IndexVMn", referenced from:
[ERROR] 19:49:47.347       _symbolic _____ SS5IndexV in FirebaseStorage(StoragePath.o)
[ERROR] 19:49:47.594   "_$sSS5countSivg", referenced from:
[ERROR] 19:49:47.612       _$s15FirebaseStorage0B8ListTaskC7enqueueyyFyycfU_ in FirebaseStorage(StorageListTask.o)
[ERROR] 19:49:47.612       _$s15FirebaseStorage0B18GetDownloadURLTaskC33downloadURLFromMetadataDictionaryy10Foundation3URLVSgSDyS2SGF in FirebaseStorage(StorageGetDownloadURLTask.o)
[ERROR] 19:49:47.612       _$s15FirebaseStorage0B0C11useEmulator8withHost4portySS_SitF in FirebaseStorage(Storage.o)
[ERROR] 19:49:47.612       _$s15FirebaseStorage0B10ListResultC4with9referenceACSDySSypG_AA0B9ReferenceCtcfCTf4ggd_n in FirebaseStorage(StorageListResult.o)
[ERROR] 19:49:47.612       _$s15FirebaseStorage0B4PathC5childyACSSF in FirebaseStorage(StoragePath.o)
[ERROR] 19:49:47.612       _$s15FirebaseStorage0B4PathC6parentACSgyF in FirebaseStorage(StoragePath.o)
[ERROR] 19:49:47.612       _$s15FirebaseStorage0B4PathC4path5GSURIACSS_tKFZTf4nd_n in FirebaseStorage(StoragePath.o)
[ERROR] 19:49:47.612       ...
[ERROR] 19:49:47.859   "_$sSS5index5afterSS5IndexVAD_tF", referenced from:
[ERROR] 19:49:47.877       _$s15FirebaseStorage0B10ListResultC4with9referenceACSDySSypG_AA0B9ReferenceCtcfCTf4ggd_n in FirebaseStorage(StorageListResult.o)
[ERROR] 19:49:47.877       _$sSlsE5split9maxSplits25omittingEmptySubsequences14whereSeparatorSay11SubSequenceQzGSi_S2b7ElementQzKXEtKFSs_Tg5 in FirebaseStorage(StoragePath.o)
[ERROR] 19:49:47.877       _$s15FirebaseStorage0B4PathC4path5GSURIACSS_tKFZTf4nd_n in FirebaseStorage(StoragePath.o)
[ERROR] 19:49:48.117   "_$sSS5index6beforeSS5IndexVAD_tF", referenced from:
[ERROR] 19:49:48.136       _$s15FirebaseStorage0B4PathC4path5GSURIACSS_tKFZTf4nd_n in FirebaseStorage(StoragePath.o)
[ERROR] 19:49:48.380   "_$sSS6appendyySSF", referenced from:
[ERROR] 19:49:48.398       _$s15FirebaseStorage0B15TokenAuthorizerC16authorizeRequest_17completionHandlerySo19NSMutableURLRequestCSg_ys5Error_pSgctF in FirebaseStorage(StorageTokenAuthorizer.o)
[ERROR] 19:49:48.398       _$s15FirebaseStorage0B15TokenAuthorizerC16authorizeRequest_17completionHandlerySo19NSMutableURLRequestCSg_ys5Error_pSgctFySSSg_AJtcfU_ in FirebaseStorage(StorageTokenAuthorizer.o)
[ERROR] 19:49:48.398

**Comment by dkimitsa** [comment]
hi, please check if you have `<swiftSupport/>` in your `robovm.xml`

**Comment by dkimitsa** [comment]
also here is a sample that compiles
https://github.com/dkimitsa/alt-pods-tests/tree/master/firebase-storage

closing, please re-open if issue still there
