### ISSUE TITLE
Multiple frameworks missing from Firebase robopods

### ISSUE THREAD

**Issue by CoderBaron** [dkimitsa/robovm-robopods#25]
`<framework>FirebaseSessions</framework>` is missing in Crashlytics and Performance
`<framework>FirebaseCoreExtension</framework>` is missing in Crashlytics, Firestore, Functions, Performance and Storage
`<framework>PromisesSwift</framework>` is missing in Crashlytics and Performance

**Comment by metaphore** [comment]
Altpods - `1.32.0-SNAPSHOT`
Firebase SDK - `10.11.0`
I'm having the same issue. Can confirm, these are the exact 3 missing frameworks.

**Comment by dkimitsa** [comment]
hi, thanks for reporting 
will be fixed today with new alt-pods

**Comment by dkimitsa** [comment]
1.33.0-SNAPSHOT [was pushed](https://dkimitsa.github.io/2023/09/23/altpods-update/)
this issue took a while as its bit messy when it comes to FIR dependencies, as there are few sources where these can checked:
- `Firebase.zip/METADATA.md` -- not sure it is up to date and some frameworks are missing;
- [scripts/dumpdeps.kts](https://github.com/dkimitsa/robovm-robopods/blob/alt/scripts/dumpdeps.kts) -- builds a tree of directly used dependencies, mostly accurate;
- pods specs in [source tee](https://github.com/firebase/firebase-ios-sdk) -- dep list how it is used in cocoapods.

in 1.33.0 -- dumpdeps.kts and podspec files were used to list dependencies. there few notes for initial issue:
- alt-pods doen't have Performance, Functions bindings;
- `FirebaseCoreExtension` seems not be used in `Firestore`

other moments were fixed. 
bindings were quick-tested with [alt-pods-tests](https://github.com/dkimitsa/alt-pods-tests)
