### ISSUE TITLE
Exception while creating IPA

### ISSUE THREAD

**Issue by aliyildiz1980** [dkimitsa/robovm-robopods#28]
I get the error below while creating the iOS IPA. A test project is attached. The frameworks are normally located under ios/libs folder. But I deleted to decrease the size.

Development Environment:
Android Studio: Giraffe | 2022.3.1 Patch 2
Libgdx. v1.12.0
MobiVM Plugin & RoboVM: v2.3.20
Altpods: v1.33.0-SNAPSHOT
[test.zip](https://github.com/dkimitsa/robovm-robopods/files/12861483/test.zip)

[ERROR] 23:16:10.906 0  0x1049d3648  __assert_rtn + 72
[ERROR] 23:16:10.906 1  0x10498e0f0  ___Z13dispatchApplyIRKmZ15dispatchForEachIKN6mach_o13CompactUnwind11Diff24FixupEZNK2ld16LayoutExecutable18writeCompactUnwindENSt3__14spanIhLm18446744073709551615EEEyRKNS7_13SectionLayoutEE4$_26EvNSA_IT_Lm18446744073709551615EEEmT0_EUlmE_EvOSG_SI__block_invoke + 0
[ERROR] 23:16:10.906 2  0x1828c1950  _dispatch_client_callout2 + 20
[ERROR] 23:16:10.906 3  0x1828d61a4  _dispatch_apply_invoke_and_wait + 176
[ERROR] 23:16:10.906 4  0x1828d5464  _dispatch_apply_with_attr_f + 1176
[ERROR] 23:16:10.906 5  0x1828d5650  dispatch_apply + 96
[ERROR] 23:16:10.906 6  0x10498e398  ld::LayoutExecutable::writeContentWithoutLinkEdit(std::__1::span<unsigned char, 18446744073709551615ul>, unsigned long long) + 672
[ERROR] 23:16:10.906 7  0x104994020  ld::LayoutExecutable::writeToFile(char const*) + 15248
[ERROR] 23:16:10.906 8  0x1049462e8  main + 9424
[ERROR] 23:16:10.906 ld: Assertion failed: (false && "compact unwind compressed function offset doesn't fit in 24 bits"), function operator(), file Layout.cpp, line 5758.
[ERROR] 23:16:10.921 clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't create IPA
org.apache.commons.exec.ExecuteException: Command '[/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++, -o, /var/folders/g5/q82jcg2s43z1syqglsd1fpkw0000gn/T/robovm11946462152445280720.tmp/IOSLauncher, -Wl,-filelist,/var/folders/g5/q82jcg2s43z1syqglsd1fpkw0000gn/T/robovm11946462152445280720.tmp/objects0, -L, /Users/aliyildiz/.robovm-sdks/robovm-2.3.20/lib/vm/ios/arm64, -ObjC, -exported_symbols_list, /var/folders/g5/q82jcg2s43z1syqglsd1fpkw0000gn/T/robovm11946462152445280720.tmp/exported_symbols, -Wl,-no_implicit_dylibs, -Wl,-dead_strip, -F/Users/aliyildiz/.robovm/cache/ios/arm64/release/Users/aliyildiz/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.12.0/e7eb1777f7c465f6ef8cb1dad7dfc405184f17aa/gdx-platform-1.12.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs, -F/Users/aliyildiz/.robovm/cache/ios/arm64/release/Users/aliyildiz/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.12.0/e7eb1777f7c465f6ef8cb1dad7dfc405184f17aa/gdx-platform-1.12.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs/gdx.xcframework/ios-arm64, -F/Users/aliyildiz/.robovm/cache/ios/arm64/release/Users/aliyildiz/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.12.0/e7eb1777f7c465f6ef8cb1dad7dfc405184f17aa/gdx-platform-1.12.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs/ObjectAL.xcframework/ios-arm64, -F/Users/aliyildiz/.robovm/cache/ios/arm64/release/Users/aliyildiz/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-freetype-platform/1.12.0/7dc40f1944fb12594f4bf07d60d857ef031a168c/gdx-freetype-platform-1.12.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs, -F/Users/aliyildiz/.robovm/cache/ios/arm64/release/Users/aliyildiz/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-freetype-platform/1.12.0/7dc40f1944fb12594f4bf07d60d857ef031a168c/gdx-freetype-platform-1.12.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs/gdx-freetype.xcframework/ios-arm64, -F/Users/aliyildiz/Development/LoGriP/ios/libs/arm, -L/usr/lib/swift, -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos, -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/iphoneos, -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphoneos, -fPIC, --target=arm64-apple-ios8.0, -isysroot, /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk, -lrobovm-bc, -force_load, /Users/aliyildiz/.robovm-sdks/robovm-2.3.20/lib/vm/ios/arm64/librobovm-rt.a, -lrobovm-core, -lgc, -lpthread, -ldl, -lm, -lz, -liconv, -lsqlite3, -framework, Foundation, -framework, FirebaseCore, -framework, FirebaseCoreInternal, -framework, GoogleUtilities, -framework, FBLPromises, -framework, gdx, -framework, ObjectAL, -framework, FirebaseAuth, -framework, GTMSessionFetcher, -framework, FirebaseAppCheckInterop, -framework, RecaptchaInterop, -framework, gdx-freetype, -framework, GoogleMobileAds, -framework, UserMessagingPlatform, -framework, GoogleAppMeasurement, -framework, nanopb, -framework, GoogleUtilities, -framework, FBLPromises, -framework, JavaScriptCore, -framework, FirebaseFirestore, -framework, abseil, -framework, BoringSSL-GRPC, -framework, gRPC-C++, -framework, gRPC-Core, -framework, leveldb-library, -framework, nanopb, -framework, OpenGLES, -framework, FirebaseRemoteConfig, -framework, FirebaseABTesting, -framework, FirebaseInstallations, -framework, FirebaseStorage, -framework, FirebaseAppCheckInterop, -framework, FirebaseAuthInterop, -framework, FirebaseCoreExtension, -framework, GTMSessionFetcher, -framework, UIKit, -framework, OpenGLES, -framework, QuartzCore, -framework, CoreGraphics, -framework, OpenAL, -framework, AudioToolbox, -framework, AVFoundation, -lz, -framework, MobileCoreServices, -Xlinker, -rpath, -Xlinker, /usr/lib/swift, -Xlinker, -rpath, -Xlinker, @executable_path/Frameworks, -Xlinker, -rpath, -Xlinker, @loader_path/Frameworks]' failed  (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.robovm.compiler.util.Executor.exec(Executor.java:344)
	at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:472)
	at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:275)
	at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:333)
	at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:268)
	at org.robovm.compiler.Linker.link(Linker.java:449)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:520)
	at org.robovm.compiler.AppCompiler.build(AppCompiler.java:957)
	at org.robovm.idea.compilation.RoboVmCompileTask$1.doCompile(RoboVmCompileTask.java:107)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:69)

**Comment by dkimitsa** [comment]
its not related to alt-pods. this was introduced by XCode15. 
check this issue for reference and solution https://github.com/MobiVM/robovm/issues/750
