### ISSUE TITLE
Google Mobile Ads Sample code is outdated

### ISSUE THREAD

**Issue by JojoIce** [dkimitsa/robovm-robopods#29]
I could not get the sample code to work, and the internet indicate that the classes used in the sample are outdated.

https://github.com/dkimitsa/robovm-robopods/tree/alt/firebase/ios-google-mobile-ads#sample-code

I guess that it now should be:

org.robovm.pods.google.mobileads.GADInterstitialAd;
org.robovm.pods.google.mobileads.GADRewardedInterstitialAd;

Maybe it can mostly be copied from here: https://github.com/dkimitsa/alt-pods-tests/blob/master/firebase-google-ads/src/main/java/io/github/dkimitsa/tests/DemoGoogleAds.java

**Comment by dkimitsa** [comment]
thx, fixed in v1.38.0
https://github.com/dkimitsa/robovm-robopods/tree/dev/v1.38.0/firebase/ios-google-mobile-ads
