### ISSUE TITLE
Issue with ClearAds altpod

### ISSUE THREAD

**Issue by vminc** [dkimitsa/robovm-robopods#30]
Hello, we're trying to use the ClearAds altpods and run into this issue. It happens when an ad is about to be present (Banner or Interstitial):

Terminating app due to uncaught exception 'org.robovm.objc.ObjCClassNotFoundException', reason: 'org.robovm.objc.ObjCClassNotFoundException: Could not find Java class corresponding to Objective-C class: CleverAdsSolutions.ImpressionWrapper.

Is there an example of integrating with this altpod succesfully?

**Comment by dkimitsa** [comment]
@vminc 
hello
not enough information here, please provide :
- version of alt-pods;
- version of CAS used;
- source code snipped to reproduce 
- symbolicated crash log

thanks

**Comment by dkimitsa** [comment]
there is an issue in RoboVM obj-c runtime (not related to alt-pod binding). 
currently you can workaround it by declaring following class somewhere:
```
    @NativeClass("CleverAdsSolutions.ImpressionWrapper")
    static class CleverAdsSolutions_ImpressionWrapper extends ObjCObject implements CASStatusHandler {
        /*<bind>*/static { ObjCRuntime.bind(CleverAdsSolutions_ImpressionWrapper.class); }/*</bind>*/
        @Override native public CASType getAdType();
        @Override native public String getNetwork();
        @Override native public double getCpm();
        @Override native public CASPriceAccuracy getPriceAccuracy();
        @Override native public String getVersionInfo();
        @Override native public String getCreativeIdentifier();
        @Override native public String getIdentifier();
        @Override native public long getImpressionDepth();
        @Override native public double getLifetimeRevenue();
        @Override native public String getStatus();
        @Override native public String getError();
        @Override native public boolean isAdCached();
        @Override native public void toggleIgnoreMode();
    }
```

make sure it is not removed by tree-sharer, just reference it somewhere:
```
System.out.println(CleverAdsSolutions_ImpressionWrapper.class);
```

**Comment by dkimitsa** [comment]
fix in RoboVM
https://github.com/MobiVM/robovm/pull/784
