### ISSUE TITLE
Not able to use Admob rewarded video ads (GADRewardedAd)

### ISSUE THREAD

**Issue by DavidPDev** [dkimitsa/robovm-robopods#9]
We have changed the old `GADRewardBasedVideoAd` to `GADRewardedAd` and now we are getting the error:

IOSLauncher[15598:1804682] -[GADRewardedAd initWithAdUnitID:]: unrecognized selector sent to instance 0x600000360340

on this line:

gadRewardedAd = new GADRewardedAd(adunit);

Is there any guide / hint on how to use the new GADRewardedAd class?

All libraries and SDKs are up to date.
Using version 1.14.0-SNAPSHOT and last firebase.zip file.

**Comment by DavidPDev** [comment]
This is the complete error log:
```2021-03-08 18:15:31.390 IOSLauncher[16709:1908635] -[GADRewardedAd initWithAdUnitID:]: unrecognized selector sent to instance 0x60000017bdc0
            2021-03-08 18:15:31.502 IOSLauncher[16709:1908635] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GADRewardedAd initWithAdUnitID:]: unrecognized selector sent to instance 0x60000017bdc0'
                    *** First throw call stack:
            (
                    0   CoreFoundation                      0x0000000113301af6 __exceptionPreprocess + 242
            1   libobjc.A.dylib                     0x0000000115c3ee78 objc_exception_throw + 48
            2   CoreFoundation                      0x00000001133106f7 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
            3   CoreFoundation                      0x0000000113306036 ___forwarding___ + 1489
            4   CoreFoundation                      0x0000000113308068 _CF_forwarding_prep_0 + 120
            5   IOSLauncher                         0x000000010e7ac9e3 [J]org.robovm.pods.google.mobileads.GADRewardedAd.$m$initWithAdUnitID$(Lorg/robovm/pods/google/mobileads/GADRewardedAd;Lorg/robovm/objc/Selector;Ljava/lang/String;)J + 177
            6   IOSLauncher                         0x000000010e7abbb3 [J]org.robovm.pods.google.mobileads.GADRewardedAd.init(Ljava/lang/String;)J + 88
            7   IOSLauncher                         0x000000010e7ab627 [J]org.robovm.pods.google.mobileads.GADRewardedAd.<init>(Ljava/lang/String;)V + 62
            8   IOSLauncher                         0x000000010ddafd45 [j]com.LibIOS.Utils.IOSRewardedController$1$1.didDismiss(Lorg/robovm/pods/google/mobileads/GADRewardedAd;)V[lookup] + 501
            9   IOSLauncher                         0x000000010df02e3a [J]com.LibIOS.Utils.IOSRewardedController$3.invoke(Lorg/robovm/pods/google/mobileads/GADRequestError;)V + 1388560
            10  IOSLauncher                         0x000000010df10267 [J]com.LibIOS.Utils.IOSRewardedController$3.invoke(Lorg/robovm/pods/google/mobileads/GADRequestError;)V + 1442877
            11  IOSLauncher                         0x000000010df10d99 [J]com.LibIOS.Utils.IOSRewardedController$3.invoke(Lorg/robovm/pods/google/mobileads/GADRequestError;)V + 1445743
            12  IOSLauncher                         0x000000010df0f238 [J]com.LibIOS.Utils.IOSRewardedController$3.invoke(Lorg/robovm/pods/google/mobileads/GADRequestError;)V + 1438734
            13  GLKit                               0x000000013d5336d5 -[GLKViewController _updateAndDraw] + 573
            14  QuartzCore                          0x0000000111baa2b9 _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 755
            15  QuartzCore                          0x0000000111c8fdbc _ZL22display_timer_callbackP12__CFMachPortPvlS1_ + 639
            16  CoreFoundation                      0x000000011323d9d8 __CFMachPortPerform + 157
            17  CoreFoundation                      0x0000000113270c82 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
            18  CoreFoundation                      0x0000000113270023 __CFRunLoopDoSource1 + 614
            19  CoreFoundation                      0x000000011326a4f2 __CFRunLoopRun + 2353
            20  CoreFoundation                      0x00000001132696d6 CFRunLoopRunSpecific + 567
            21  GraphicsServices                    0x00000001207eedb3 GSEventRunModal + 139
            22  UIKitCore                           0x0000000118e05cf7 -[UIApplication _run] + 912
            23  UIKitCore                           0x0000000118e0aba8 UIApplicationMain + 101
            24  IOSLauncher                         0x000000010e5102f0 [J]org.robovm.apple.coregraphics.CGPDFPage.<clinit>()V + 1297399
            25  IOSLauncher                         0x000000010e50f842 [J]org.robovm.apple.coregraphics.CGPDFPage.<clinit>()V + 1294665
            26  IOSLauncher                         0x000000010e50e7f4 [J]org.robovm.apple.coregraphics.CGPDFPage.<clinit>()V + 1290491
            27  IOSLauncher                         0x000000010e113aff [J]com.LibIOS.Utils.IOSRewardedController$3.invoke(Lorg/robovm/pods/google/mobileads/GADRequestError;)V + 3554517
            28  IOSLauncher                         0x000000010e7e437e catch_exception_raise + 95017
            29  IOSLauncher                         0x000000010e7d9b24 catch_exception_raise + 51919
            30  IOSLauncher                         0x000000010e7dc1bf catch_exception_raise + 61802
            31  IOSLauncher                         0x000000010e7dc28f catch_exception_raise + 62010
            32  IOSLauncher                         0x000000010e7d4a9e catch_exception_raise + 31305
            33  IOSLauncher                         0x000000010e7cab00 [J]org.robovm.pods.google.mobileads.GADServerSideVerificationOptions.<clinit>()V + 111797
            34  libdyld.dylib                       0x00000001158463e9 start + 1
            35  ???                                 0x0000000000000002 0x0 + 2
)
            libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by dkimitsa** [comment]
Hi, 1.14.0-SNAPSHOT bindings are made for GAD version 7.69.0, but recent firebase release ships GoogleMobileAds v8.0.0. There is bunch of dramatic changes in v8 like method missing in your sample. 
So either use v7.69 or wait for 1.15.0 to be published. It is in development and you can test it by building yourself from the branch https://github.com/dkimitsa/robovm-robopods/tree/dev-1.15/

**Comment by DavidPDev** [comment]
Great! Thank you! I'll test new 1.15 and comment.

**Comment by cellcrowd** [comment]
'you can test it by building yourself', is there anything to build? I am only using the java files from this repo.. v1.15 with some Firebase frameworks added from latest Firebase zip is crashing on startup though with no stacktrace

**Comment by dkimitsa** [comment]
@cellcrowd 
going to push snapshot tonight, meanwhile could you please share a code snippet that is crashing for you ?

**Comment by cellcrowd** [comment]
@dkimitsa unfortunately the codebase is huge however it still crashes when commenting out all of the firebase related code so I don't think it is related to my end. In addition it didn't crash when using v1.14. This issue actually led me to updating as I had already been searching for GAD v8 robopod and wasn't aware of a dev branch. I'll let you know how the new snapshot works out for me once pushed, thanks!

[edit] I will also double check my frameworks, are you aware of any new ones / dependencies in this Firebase update I might have missed?

**Comment by cellcrowd** [comment]
@dkimitsa I narrowed the crash down to GADInterstitialAd.load and GADRewardedAd.load calls. Banner is working fine. As banners are not using them, it seems the crash is related to static method calls?

[edit] I tried adding a strongref to the VoidBlock2<GADInterstitialAd, NSError> object that is passed to the last parameter to no avail

[edit2], of course I should have tested first with an empty VoidBlock2, which worked. This made me narrow it down to the setFullScreenContentDelegate call:

```
GADInterstitialAd.load(id, request, new VoidBlock2<GADInterstitialAd, NSError>() {
  @Override
  public void invoke(GADInterstitialAd ad, NSError error) {
    if(error != null) {
      //handle error
    }else {
      if(ad != null) {
        ad.setFullScreenContentDelegate(new GADFullScreenContentDelegate() {
          @Override
          public void adDidRecordImpression(GADFullScreenPresentingAd ad) {}
          @Override
          public void didFailToPresentFullScreenContent(GADFullScreenPresentingAd ad, NSError error) {}
          @Override
          public void adDidPresentFullScreenContent(GADFullScreenPresentingAd ad) {}
          @Override
          public void adDidDismissFullScreenContent(GADFullScreenPresentingAd ad) {}
        });
      }
    }
  }
});
```
also tested with a strongref

[final edit] I found the culprit, I should have used GADFullScreenContentDelegateAdapter instead of GADFullScreenContentDelegate, everything working now (v1.15)! Many thanks for this repo!

**Comment by dkimitsa** [comment]
hi, thanks for comments, didn't see it in time so tested myself and it was working. 
Indeed you should extend from NSObject when passing the delegate.  

Also I have updated Firebase to v7.8.0 and GAD to 8.1.0. 
Also dev 1.15.0-SNAPSHOT version have been pushed to Sonatype so you can use it just with gradle. 

@DavidPDev  please  confirm it is working for you (and close the issue).
Thx

**Comment by DavidPDev** [comment]
> hi, thanks for comments, didn't see it in time so tested myself and it was working.
> Indeed you should extend from NSObject when passing the delegate.
> 
> Also I have updated Firebase to v7.8.0 and GAD to 8.1.0.
> Also dev 1.15.0-SNAPSHOT version have been pushed to Sonatype so you can use it just with gradle.
> 
> @DavidPDev please confirm it is working for you (and close the issue).
> Thx

Great news. Thank you!

I will test it ASAP, but I have to change some code as the GADInterstitial and GADRewardedAd are now used differently.

Just one question: The firebase.zip file should be downloaded from the Google Firebase web?
If the firebase.zip file doesn't match with your build may have some conflict with internal libraries. Or not?

**Comment by dkimitsa** [comment]
@DavidPDev 
I usually download it from GitHub Release [page](https://github.com/firebase/firebase-ios-sdk/releases)
Bindings are done against very specific version. Other versions of Firebase libs might introduce not-compatible API changes (like happened with GAD). Its better to use exact version of binaries bindings were done for (but newer might work as well, if there was no API changes)

**Comment by DavidPDev** [comment]
> @DavidPDev
> I usually download it from GitHub Release [page](https://github.com/firebase/firebase-ios-sdk/releases)
> Bindings are done against very specific version. Other versions of Firebase libs might introduce not-compatible API changes (like happened with GAD). Its better to use exact version of binaries bindings were done for (but newer might work as well, if there was no API changes)

Ok, Perfect. I was always using the lastest firebase.zip file (from Firebase help web) so maybe binaries where not matching the pods. Now I understand it.
I suggest you link somehow every new version of the pods with its corresponding firebase version.
Thank you again!.

**Comment by dkimitsa** [comment]
@DavidPDev it is listed in readme file for every group of pods (and root one as well). [example](https://github.com/dkimitsa/robovm-robopods/blob/alt/firebase/README.md)

**Comment by dkimitsa** [comment]
@DavidPDev  going to close this issue tonight, does it work for you ?

**Comment by DavidPDev** [comment]
> @DavidPDev going to close this issue tonight, does it work for you ?

Well, I've done some tests and seem to work ok! Sorry for the delay.
I'll publish a LIVE update tomorrow on the iOS app store (cross fingers).
I close the issue.
In the following days I will update with news.
Again, thank you a lot @dkimitsa for your support and @cellcrowd for showing a sample (I had also to change to GADFullScreenContentDelegateAdaptor to make it work).
